### ISSUE TITLE
search-bar is not loaded / displayed in OTRS 4.0.11

### ISSUE THREAD

**Issue by aebgit** [znuny/Znuny4OTRS-CISearch#1]
Hi,

I've installed the Znuny4OTRS-CISearch 1.0.4 via Znuny4OTRS-Repo in my OTRS 4.0.11 installation (via WebFrontend) but the search-bar does not show up. 

My ITSMConfigurationManagement package has Version 4.0.11 (so its consistent withthe rest of my OTRS).

I have tried the following steps so far:
- logged in again to OTRS
- restarted the webserver
- restarted the whole server
- re-installed the package via WebFrontend

Do you have any ideas?

Thanks in advance!
Andreas

**Comment by thorsteneckel** [comment]
Hi Andreas!

Thanks for your feedback. Have you checked the SysConfig "Znuny4OTRSCISearch::SearchParams###DefaultClassName" ( https://github.com/znuny/Znuny4OTRS-CISearch/blob/master/Kernel/Config/Files/Znuny4OTRSCISearch.xml#L37 )?

You have to define which agent roles get search for which CI classes. There is a deficit in the documentation of this features. We will take care of it.

@dennybresch Could you please improve the documentationS (https://github.com/znuny/Znuny4OTRS-CISearch/blob/master/doc/de/feature.md#znuny4otrscisearchsearchparamsdefaultclassname) of this feature? It's not intuitive. I would propose another SysConfig for a default Class (Computer) which will be used if no Class could be found in the mapping (https://github.com/znuny/Znuny4OTRS-CISearch/blob/master/Kernel/Modules/Znuny4OTRSCISearch.pm#L46).

**Comment by aebgit** [comment]
Hi Thorsten,

thanks for the hint - unfortunately the searchbar still doesn't show up. 
Here is what I've tried:
- entered existing roles of that I'm member into Znuny4OTRSCISearch::SearchParams###DefaultClassName
- created a new role with the name of one of the examples (computerrole), added some existent agents to it and performed log-off/log-on

By the way, I can't give only ONE role access to multiple CMDB-classes (via Webinterface). When I enter the same role into each line and click on 'Update', the list is shrinked to only one line (= one CI-class).

We have a flat hierarchy in our it-department, so we dont really need to filter the search-possibilities. Is there an easy way to disable that function?

Best regards
Andreas

**Comment by thorsteneckel** [comment]
Hi Andreas! @dennybresch will take care of that. This functionality should be easy to use and suitable for everybody. We will find a solution :) It may take some time cause we have some support customers we have to take care about.

**Comment by aebgit** [comment]
Thanks for your help!

**Comment by rkaldung** [comment]
Hi Andreas,

You don't give access to the CMDB classes. This is done via the General catalog where you're able to assign groups to your CMDB classes.

This addon adds just a short way to search for CIs where you have first choose the class and then enter your search terms.
![2016-02-09 at 2 15 pm](https://cloud.githubusercontent.com/assets/378324/12917105/a22202b4-cf37-11e5-988b-3656203d7bd8.png)

The role/group <-> class configuration does only a presetting of a class to search in.

**Comment by aebgit** [comment]
OK, now I understand what the roles are used for here.
If you need further information about my installation to solve my issue (the search-field doesn't sho up at all) just tell me.

**Comment by aebgit** [comment]
Today I noticed, that in "Admin -> System Log" lots of the following messages are logged:

Mon Feb 29 14:22:32 2016 error OTRS-CGI-25 Type of arg 1 to keys must be hash (not hash element) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/Znuny4OTRSCISearch.pm line 89, near "} ) "

**Comment by dennykorsukewitz** [comment]
Hi @aebgit,
we fixed some small issues in version 1.0.5.
We added DefaultClassName to user preferences and a added FallbackDefaultClassName to SysConfig.

If you don't use roles, please make sure that your SysConfig is like this:
( **Znuny4OTRSCISearch::SearchParams###DefaultClassName must be _disabled_**)

![cisearch](https://cloud.githubusercontent.com/assets/3249687/13529370/2175babe-e21c-11e5-98ee-cffc0e899576.png)

Best regards
Denny

**Comment by aebgit** [comment]
@dennybresch Thank you - the issue is solved!!
