### ISSUE TITLE
Bug - CI search disappears after the refresh interval

### ISSUE THREAD

**Issue by KaiHerlemann** [znuny/Znuny4OTRS-CISearch#10]
### Environment

- Browser: Chrome 117.0.5938.92
- Framework version: 6.5.4
- Addon version: 6.5.1

### Expected behavior

The CI search shouldn't disappear.

### Actual behavior

The CI search disappears after the refresh interval.

### How to reproduce

Just set in your settings the refresh interval.
![image](https://github.com/znuny/Znuny4OTRS-CISearch/assets/43746520/a39ae15c-0921-43be-8f08-4df768af071b)

### Additional information

This issue is related to that one which was solved by znuny/znuny#317.

**Comment by rkaldung** [comment]
Internal issue Znuny4OTRS-CISearch/-/issues/5

**Comment by rkaldung** [comment]
This issue is fixed with Znuny version that contain this [PR](https://github.com/znuny/Znuny/pull/317).
