### ISSUE TITLE
Improve default CI Search class configuration

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-CISearch#3]
Currently there is this SysConfig where the default CI Search class is defined:

https://github.com/znuny/Znuny4OTRS-CISearch/blob/master/Kernel/Config/Files/Znuny4OTRSCISearch.xml#L37

It contains dummy data that is wrong in a productive environment and is basicly a documentation. This feature should get documented as described in #2 .

Furthermore this SysConfig should be disabled by default. Only users who wish to use it should activate it. To define a global default class 'Computer' a **new** SysConfig named 'FallbackDefaultClassName' should get added. The configured value in this config should get used if no other class can't get determined.

Therefore default class selection flow should be linke:
- Check SysConfig 'DefaultClassName' (default disabled)
- If no default class could get determined check 'FallbackDefaultClassName'  (default 'Computer')

**Comment by dennykorsukewitz** [comment]
Fixed in https://github.com/znuny/Znuny4OTRS-CISearch/commit/9d613ef7fdbca85a8162c96cb2aa7e6937a9ead9
Added DefaultClassName to user preferences in https://github.com/znuny/Znuny4OTRS-CISearch/commit/a7918c1ce73e90903fcd51539a53375ff7a9c2cb
