### ISSUE TITLE
Unusable Icons

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny4OTRS-CISearch#5]
When using a slim skin in OTRS 5 with this addon let some icons in the toolbar become unusable. Executing Core.Agent.ResizeNavigationBar(1); in the browser javascript console solve the problem.

**Comment by dennykorsukewitz** [comment]
Fix bug with commit: https://github.com/znuny/Znuny4OTRS-CISearch/commit/fce90459e2c83437df1e37fde66dc99ad64e5eb1
