### ISSUE TITLE
Problem on Select Process

### ISSUE THREAD

**Issue by joserribeiro26** [znuny/Znuny4OTRS-CISearch#6]
When I chose an process the Field on search is duplicated.

![image](https://cloud.githubusercontent.com/assets/475022/15648523/90a7cc06-2641-11e6-8c13-8413c4c8352f.png)

Later select process

![image](https://cloud.githubusercontent.com/assets/475022/15648534/a0311ba0-2641-11e6-9807-a6ed7f9d66b2.png)

The package is on the last version.

1.1.10

Thanks.

**Comment by thorsteneckel** [comment]
Hi @joserribeiro26 - Thanks for reporting this issue!

@dennybresch could you please take a look it this? I think we should use 'AddJSOnDocumentCompleteIfNotExists' from our Repo ( https://github.com/znuny/Znuny4OTRS-Repo/blob/master/Kernel/Output/HTML/Layout/Znuny4OTRSRepo.pm#L335 ) here:

https://github.com/znuny/Znuny4OTRS-CISearch/blob/master/Kernel/Modules/Znuny4OTRSCISearch.pm#L116

**Comment by dennykorsukewitz** [comment]
Hi @joserribeiro26,

we fixed this bug in 1.1.3, which is now available.

Thank you for your bug report.
Best regards!

**Comment by joserribeiro26** [comment]
Thank you, problem solved.
