### ISSUE TITLE
Sort order of CI classes

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny4OTRS-CISearch#8]
What's the order of the CI class names in the list box? Looks a little bit weird: 

![image](https://cloud.githubusercontent.com/assets/378324/20007094/ff0a0c88-a29a-11e6-8b8e-fec5c44e18fb.png)

**Comment by thorsteneckel** [comment]
List is build at: https://github.com/znuny/Znuny4OTRS-CISearch/blob/master/var/httpd/htdocs/js/Core.Agent.Znuny4OTRSCISearch.js#L76

Should be done via an array instead of an object.

**Comment by dennykorsukewitz** [comment]
Fixed Issue:

![fix](https://cloud.githubusercontent.com/assets/3249687/21931135/0814ef56-d99a-11e6-8629-d61a7d33eedc.png)
