### ISSUE TITLE
NavigationBar items not dragable

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-CISearch#9]
In OTRS the navigation bar items are drag&drop-able. This allows the agent to rearrange the navigation bar items as preferred. However after installing the this addon the functionality is broken and a "not dragable" icon is shown.

This is caused by this line:
https://github.com/znuny/Znuny4OTRS-CISearch/blob/8ab94b1f843bcda2d2906129f73721bfb22602e9/var/httpd/htdocs/js/Core.Agent.Znuny4OTRSCISearch.js#L87

Since OTRS only triggers the navigation initialization:
https://github.com/OTRS/otrs/blob/d29ce846afdfb52eebed219c0671bfcc0d75e5c9/var/httpd/htdocs/js/Core.Agent.js#L246

Via:
https://github.com/OTRS/otrs/blob/d29ce846afdfb52eebed219c0671bfcc0d75e5c9/var/httpd/htdocs/js/Core.App.Responsive.js#L102

If the class is not already set:
https://github.com/OTRS/otrs/blob/d29ce846afdfb52eebed219c0671bfcc0d75e5c9/var/httpd/htdocs/js/Core.App.Responsive.js#L95

**Comment by dennykorsukewitz** [comment]
Fixed issue with commit: https://github.com/znuny/Znuny4OTRS-CISearch/commit/b0dda42678120aee94fb75c3fceb97fa1169da20
